#!/usr/bin/env ruby

require 'set'

bundle_path = File.join(File.dirname(__FILE__), 'bundle')

plugins = [
  'scrooloose/nerdtree',
  'kchmck/vim-coffee-script'
]

plugins.each do |git_repo|
  plugin_dir = File.join(bundle_path, git_repo.split('/').last)
  if File.directory? plugin_dir
    puts "updating #{plugin_dir} (#{git_repo})"
    `cd #{plugin_dir} && git pull`
  else
    puts "fetching #{git_repo}"
    `cd #{bundle_path} && git clone git@github.com:#{git_repo}`
  end
end

do_not_remove = Set.new(['.', '..'])
do_not_remove += Set.new(plugins.collect {|p| p.split('/').last})
Dir.entries(bundle_path).each do |f|
  plugin_dir = File.join(bundle_path, f)
  if File.directory?(plugin_dir) && !do_not_remove.include?(f)
    puts "removing #{plugin_dir}"
    `rm -rf #{plugin_dir}`
  end
end
